// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

/**
 * Protobuf enum {@code com.trasier.api.client.protobuf.ContentType}
 */
public enum ContentType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TEXT = 0;</code>
   */
  TEXT(0),
  /**
   * <code>XML = 1;</code>
   */
  XML(1),
  /**
   * <code>JSON = 2;</code>
   */
  JSON(2),
  /**
   * <code>SQL = 3;</code>
   */
  SQL(3),
  /**
   * <code>BINARY = 4;</code>
   */
  BINARY(4),
  /**
   * <code>ENCRYPTED = 5;</code>
   */
  ENCRYPTED(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TEXT = 0;</code>
   */
  public static final int TEXT_VALUE = 0;
  /**
   * <code>XML = 1;</code>
   */
  public static final int XML_VALUE = 1;
  /**
   * <code>JSON = 2;</code>
   */
  public static final int JSON_VALUE = 2;
  /**
   * <code>SQL = 3;</code>
   */
  public static final int SQL_VALUE = 3;
  /**
   * <code>BINARY = 4;</code>
   */
  public static final int BINARY_VALUE = 4;
  /**
   * <code>ENCRYPTED = 5;</code>
   */
  public static final int ENCRYPTED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ContentType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ContentType forNumber(int value) {
    switch (value) {
      case 0: return TEXT;
      case 1: return XML;
      case 2: return JSON;
      case 3: return SQL;
      case 4: return BINARY;
      case 5: return ENCRYPTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ContentType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          ContentType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ContentType>() {
          public ContentType findValueByNumber(int number) {
            return ContentType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return WriteServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ContentType[] VALUES = values();

  public static ContentType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ContentType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.trasier.api.client.protobuf.ContentType)
}

