// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

public interface SpanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.trasier.api.client.protobuf.SpanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
