// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

public interface SpanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.trasier.api.client.protobuf.SpanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  String getAccountId();
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <code>string spaceKey = 2;</code>
   * @return The spaceKey.
   */
  String getSpaceKey();
  /**
   * <code>string spaceKey = 2;</code>
   * @return The bytes for spaceKey.
   */
  com.google.protobuf.ByteString
      getSpaceKeyBytes();

  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  java.util.List<Span>
      getSpansList();
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  Span getSpans(int index);
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  int getSpansCount();
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  java.util.List<? extends SpanOrBuilder>
      getSpansOrBuilderList();
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  SpanOrBuilder getSpansOrBuilder(
          int index);
}
