// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

public interface SpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.trasier.api.client.protobuf.Span)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string parentId = 2;</code>
   * @return The parentId.
   */
  String getParentId();
  /**
   * <code>string parentId = 2;</code>
   * @return The bytes for parentId.
   */
  com.google.protobuf.ByteString
      getParentIdBytes();

  /**
   * <code>string traceId = 3;</code>
   * @return The traceId.
   */
  String getTraceId();
  /**
   * <code>string traceId = 3;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string conversationId = 4;</code>
   * @return The conversationId.
   */
  String getConversationId();
  /**
   * <code>string conversationId = 4;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int64 startTimestamp = 7;</code>
   * @return The startTimestamp.
   */
  long getStartTimestamp();

  /**
   * <code>int64 endTimestamp = 8;</code>
   * @return The endTimestamp.
   */
  long getEndTimestamp();

  /**
   * <code>int64 beginProcessingTimestamp = 9;</code>
   * @return The beginProcessingTimestamp.
   */
  long getBeginProcessingTimestamp();

  /**
   * <code>int64 finishProcessingTimestamp = 10;</code>
   * @return The finishProcessingTimestamp.
   */
  long getFinishProcessingTimestamp();

  /**
   * <code>map&lt;string, string&gt; tags = 11;</code>
   */
  int getTagsCount();
  /**
   * <code>map&lt;string, string&gt; tags = 11;</code>
   */
  boolean containsTags(
          String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTags();
  /**
   * <code>map&lt;string, string&gt; tags = 11;</code>
   */
  java.util.Map<String, String>
  getTagsMap();
  /**
   * <code>map&lt;string, string&gt; tags = 11;</code>
   */

  String getTagsOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tags = 11;</code>
   */

  String getTagsOrThrow(
          String key);

  /**
   * <code>map&lt;string, string&gt; features = 12;</code>
   */
  int getFeaturesCount();
  /**
   * <code>map&lt;string, string&gt; features = 12;</code>
   */
  boolean containsFeatures(
          String key);
  /**
   * Use {@link #getFeaturesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getFeatures();
  /**
   * <code>map&lt;string, string&gt; features = 12;</code>
   */
  java.util.Map<String, String>
  getFeaturesMap();
  /**
   * <code>map&lt;string, string&gt; features = 12;</code>
   */

  String getFeaturesOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; features = 12;</code>
   */

  String getFeaturesOrThrow(
          String key);

  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint incomingEndpoint = 13;</code>
   * @return Whether the incomingEndpoint field is set.
   */
  boolean hasIncomingEndpoint();
  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint incomingEndpoint = 13;</code>
   * @return The incomingEndpoint.
   */
  Endpoint getIncomingEndpoint();
  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint incomingEndpoint = 13;</code>
   */
  EndpointOrBuilder getIncomingEndpointOrBuilder();

  /**
   * <code>.com.trasier.api.client.protobuf.ContentType incomingContentType = 14;</code>
   * @return The enum numeric value on the wire for incomingContentType.
   */
  int getIncomingContentTypeValue();
  /**
   * <code>.com.trasier.api.client.protobuf.ContentType incomingContentType = 14;</code>
   * @return The incomingContentType.
   */
  ContentType getIncomingContentType();

  /**
   * <code>map&lt;string, string&gt; incomingHeader = 15;</code>
   */
  int getIncomingHeaderCount();
  /**
   * <code>map&lt;string, string&gt; incomingHeader = 15;</code>
   */
  boolean containsIncomingHeader(
          String key);
  /**
   * Use {@link #getIncomingHeaderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getIncomingHeader();
  /**
   * <code>map&lt;string, string&gt; incomingHeader = 15;</code>
   */
  java.util.Map<String, String>
  getIncomingHeaderMap();
  /**
   * <code>map&lt;string, string&gt; incomingHeader = 15;</code>
   */

  String getIncomingHeaderOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; incomingHeader = 15;</code>
   */

  String getIncomingHeaderOrThrow(
          String key);

  /**
   * <code>string incomingData = 16;</code>
   * @return The incomingData.
   */
  String getIncomingData();
  /**
   * <code>string incomingData = 16;</code>
   * @return The bytes for incomingData.
   */
  com.google.protobuf.ByteString
      getIncomingDataBytes();

  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint outgoingEndpoint = 17;</code>
   * @return Whether the outgoingEndpoint field is set.
   */
  boolean hasOutgoingEndpoint();
  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint outgoingEndpoint = 17;</code>
   * @return The outgoingEndpoint.
   */
  Endpoint getOutgoingEndpoint();
  /**
   * <code>.com.trasier.api.client.protobuf.Endpoint outgoingEndpoint = 17;</code>
   */
  EndpointOrBuilder getOutgoingEndpointOrBuilder();

  /**
   * <code>.com.trasier.api.client.protobuf.ContentType outgoingContentType = 18;</code>
   * @return The enum numeric value on the wire for outgoingContentType.
   */
  int getOutgoingContentTypeValue();
  /**
   * <code>.com.trasier.api.client.protobuf.ContentType outgoingContentType = 18;</code>
   * @return The outgoingContentType.
   */
  ContentType getOutgoingContentType();

  /**
   * <code>map&lt;string, string&gt; outgoingHeader = 19;</code>
   */
  int getOutgoingHeaderCount();
  /**
   * <code>map&lt;string, string&gt; outgoingHeader = 19;</code>
   */
  boolean containsOutgoingHeader(
          String key);
  /**
   * Use {@link #getOutgoingHeaderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getOutgoingHeader();
  /**
   * <code>map&lt;string, string&gt; outgoingHeader = 19;</code>
   */
  java.util.Map<String, String>
  getOutgoingHeaderMap();
  /**
   * <code>map&lt;string, string&gt; outgoingHeader = 19;</code>
   */

  String getOutgoingHeaderOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; outgoingHeader = 19;</code>
   */

  String getOutgoingHeaderOrThrow(
          String key);

  /**
   * <code>string outgoingData = 20;</code>
   * @return The outgoingData.
   */
  String getOutgoingData();
  /**
   * <code>string outgoingData = 20;</code>
   * @return The bytes for outgoingData.
   */
  com.google.protobuf.ByteString
      getOutgoingDataBytes();
}
