// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

/**
 * Protobuf type {@code com.trasier.api.client.protobuf.SpanRequest}
 */
public  final class SpanRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.trasier.api.client.protobuf.SpanRequest)
        SpanRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpanRequest.newBuilder() to construct.
  private SpanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpanRequest() {
    accountId_ = "";
    spaceKey_ = "";
    spans_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpanRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpanRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            accountId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            spaceKey_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              spans_ = new java.util.ArrayList<Span>();
              mutable_bitField0_ |= 0x00000001;
            }
            spans_.add(
                input.readMessage(Span.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        spans_ = java.util.Collections.unmodifiableList(spans_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WriteServiceOuterClass.internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WriteServiceOuterClass.internal_static_com_trasier_api_client_protobuf_SpanRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpanRequest.class, SpanRequest.Builder.class);
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 1;
  private volatile Object accountId_;
  /**
   * <code>string accountId = 1;</code>
   * @return The accountId.
   */
  public String getAccountId() {
    Object ref = accountId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <code>string accountId = 1;</code>
   * @return The bytes for accountId.
   */
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    Object ref = accountId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPACEKEY_FIELD_NUMBER = 2;
  private volatile Object spaceKey_;
  /**
   * <code>string spaceKey = 2;</code>
   * @return The spaceKey.
   */
  public String getSpaceKey() {
    Object ref = spaceKey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      spaceKey_ = s;
      return s;
    }
  }
  /**
   * <code>string spaceKey = 2;</code>
   * @return The bytes for spaceKey.
   */
  public com.google.protobuf.ByteString
      getSpaceKeyBytes() {
    Object ref = spaceKey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      spaceKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPANS_FIELD_NUMBER = 3;
  private java.util.List<Span> spans_;
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  public java.util.List<Span> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  public java.util.List<? extends SpanOrBuilder>
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  public Span getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
   */
  public SpanOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountId_);
    }
    if (!getSpaceKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, spaceKey_);
    }
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(3, spans_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountId_);
    }
    if (!getSpaceKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, spaceKey_);
    }
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, spans_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpanRequest)) {
      return super.equals(obj);
    }
    SpanRequest other = (SpanRequest) obj;

    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (!getSpaceKey()
        .equals(other.getSpaceKey())) return false;
    if (!getSpansList()
        .equals(other.getSpansList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + SPACEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getSpaceKey().hashCode();
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpanRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpanRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpanRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpanRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpanRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpanRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpanRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpanRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpanRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SpanRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpanRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpanRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpanRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.trasier.api.client.protobuf.SpanRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.trasier.api.client.protobuf.SpanRequest)
          SpanRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WriteServiceOuterClass.internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WriteServiceOuterClass.internal_static_com_trasier_api_client_protobuf_SpanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpanRequest.class, SpanRequest.Builder.class);
    }

    // Construct using com.trasier.api.client.protobuf.SpanRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSpansFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      accountId_ = "";

      spaceKey_ = "";

      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        spansBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WriteServiceOuterClass.internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor;
    }

    @Override
    public SpanRequest getDefaultInstanceForType() {
      return SpanRequest.getDefaultInstance();
    }

    @Override
    public SpanRequest build() {
      SpanRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SpanRequest buildPartial() {
      SpanRequest result = new SpanRequest(this);
      int from_bitField0_ = bitField0_;
      result.accountId_ = accountId_;
      result.spaceKey_ = spaceKey_;
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpanRequest) {
        return mergeFrom((SpanRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpanRequest other) {
      if (other == SpanRequest.getDefaultInstance()) return this;
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        onChanged();
      }
      if (!other.getSpaceKey().isEmpty()) {
        spaceKey_ = other.spaceKey_;
        onChanged();
      }
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
            spansBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpanRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpanRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object accountId_ = "";
    /**
     * <code>string accountId = 1;</code>
     * @return The accountId.
     */
    public String getAccountId() {
      Object ref = accountId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string accountId = 1;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountId = 1;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      accountId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accountId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {

      accountId_ = getDefaultInstance().getAccountId();
      onChanged();
      return this;
    }
    /**
     * <code>string accountId = 1;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      accountId_ = value;
      onChanged();
      return this;
    }

    private Object spaceKey_ = "";
    /**
     * <code>string spaceKey = 2;</code>
     * @return The spaceKey.
     */
    public String getSpaceKey() {
      Object ref = spaceKey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        spaceKey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string spaceKey = 2;</code>
     * @return The bytes for spaceKey.
     */
    public com.google.protobuf.ByteString
        getSpaceKeyBytes() {
      Object ref = spaceKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        spaceKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string spaceKey = 2;</code>
     * @param value The spaceKey to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      spaceKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string spaceKey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpaceKey() {

      spaceKey_ = getDefaultInstance().getSpaceKey();
      onChanged();
      return this;
    }
    /**
     * <code>string spaceKey = 2;</code>
     * @param value The bytes for spaceKey to set.
     * @return This builder for chaining.
     */
    public Builder setSpaceKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      spaceKey_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Span> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        spans_ = new java.util.ArrayList<Span>(spans_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Span, Span.Builder, SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public java.util.List<Span> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Span getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder setSpans(
        int index, Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder setSpans(
        int index, Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder addSpans(Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder addSpans(
        int index, Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder addSpans(
        Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder addSpans(
        int index, Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder addAllSpans(
        Iterable<? extends Span> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Span.Builder getSpansBuilder(
        int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public SpanOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public java.util.List<? extends SpanOrBuilder>
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Span.Builder addSpansBuilder() {
      return getSpansFieldBuilder().addBuilder(
          Span.getDefaultInstance());
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public Span.Builder addSpansBuilder(
        int index) {
      return getSpansFieldBuilder().addBuilder(
          index, Span.getDefaultInstance());
    }
    /**
     * <code>repeated .com.trasier.api.client.protobuf.Span spans = 3;</code>
     */
    public java.util.List<Span.Builder>
         getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Span, Span.Builder, SpanOrBuilder>
        getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Span, Span.Builder, SpanOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.trasier.api.client.protobuf.SpanRequest)
  }

  // @@protoc_insertion_point(class_scope:com.trasier.api.client.protobuf.SpanRequest)
  private static final SpanRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpanRequest();
  }

  public static SpanRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpanRequest>
      PARSER = new com.google.protobuf.AbstractParser<SpanRequest>() {
    @Override
    public SpanRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpanRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpanRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpanRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public SpanRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

