// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteService.proto

package com.trasier.api.client.protobuf;

public final class WriteServiceOuterClass {
  private WriteServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_SpanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_SpanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_SpanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Span_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Span_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Span_FeaturesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Span_FeaturesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Span_IncomingHeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Span_IncomingHeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Span_OutgoingHeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Span_OutgoingHeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trasier_api_client_protobuf_Endpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_trasier_api_client_protobuf_Endpoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022WriteService.proto\022\037com.trasier.api.cl" +
      "ient.protobuf\"\035\n\014SpanResponse\022\r\n\005count\030\001" +
      " \001(\005\"h\n\013SpanRequest\022\021\n\taccountId\030\001 \001(\t\022\020" +
      "\n\010spaceKey\030\002 \001(\t\0224\n\005spans\030\003 \003(\0132%.com.tr" +
      "asier.api.client.protobuf.Span\"\242\010\n\004Span\022" +
      "\n\n\002id\030\001 \001(\t\022\020\n\010parentId\030\002 \001(\t\022\017\n\007traceId" +
      "\030\003 \001(\t\022\026\n\016conversationId\030\004 \001(\t\022\014\n\004name\030\005" +
      " \001(\t\022\016\n\006status\030\006 \001(\t\022\026\n\016startTimestamp\030\007" +
      " \001(\003\022\024\n\014endTimestamp\030\010 \001(\003\022 \n\030beginProce" +
      "ssingTimestamp\030\t \001(\003\022!\n\031finishProcessing" +
      "Timestamp\030\n \001(\003\022=\n\004tags\030\013 \003(\0132/.com.tras" +
      "ier.api.client.protobuf.Span.TagsEntry\022E" +
      "\n\010features\030\014 \003(\01323.com.trasier.api.clien" +
      "t.protobuf.Span.FeaturesEntry\022C\n\020incomin" +
      "gEndpoint\030\r \001(\0132).com.trasier.api.client" +
      ".protobuf.Endpoint\022I\n\023incomingContentTyp" +
      "e\030\016 \001(\0162,.com.trasier.api.client.protobu" +
      "f.ContentType\022Q\n\016incomingHeader\030\017 \003(\01329." +
      "com.trasier.api.client.protobuf.Span.Inc" +
      "omingHeaderEntry\022\024\n\014incomingData\030\020 \001(\t\022C" +
      "\n\020outgoingEndpoint\030\021 \001(\0132).com.trasier.a" +
      "pi.client.protobuf.Endpoint\022I\n\023outgoingC" +
      "ontentType\030\022 \001(\0162,.com.trasier.api.clien" +
      "t.protobuf.ContentType\022Q\n\016outgoingHeader" +
      "\030\023 \003(\01329.com.trasier.api.client.protobuf" +
      ".Span.OutgoingHeaderEntry\022\024\n\014outgoingDat" +
      "a\030\024 \001(\t\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\032/\n\rFeaturesEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0325\n\023IncomingHeaderE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0325\n\023" +
      "OutgoingHeaderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"K\n\010Endpoint\022\014\n\004name\030\001 \001(\t\022\021\n" +
      "\tipAddress\030\002 \001(\t\022\014\n\004port\030\003 \001(\t\022\020\n\010hostna" +
      "me\030\004 \001(\t*N\n\013ContentType\022\010\n\004TEXT\020\000\022\007\n\003XML" +
      "\020\001\022\010\n\004JSON\020\002\022\007\n\003SQL\020\003\022\n\n\006BINARY\020\004\022\r\n\tENC" +
      "RYPTED\020\0052w\n\014WriteService\022g\n\004send\022,.com.t" +
      "rasier.api.client.protobuf.SpanRequest\032-" +
      ".com.trasier.api.client.protobuf.SpanRes" +
      "ponse(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_trasier_api_client_protobuf_SpanResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_trasier_api_client_protobuf_SpanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_SpanResponse_descriptor,
        new String[] { "Count", });
    internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_trasier_api_client_protobuf_SpanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_SpanRequest_descriptor,
        new String[] { "AccountId", "SpaceKey", "Spans", });
    internal_static_com_trasier_api_client_protobuf_Span_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_trasier_api_client_protobuf_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Span_descriptor,
        new String[] { "Id", "ParentId", "TraceId", "ConversationId", "Name", "Status", "StartTimestamp", "EndTimestamp", "BeginProcessingTimestamp", "FinishProcessingTimestamp", "Tags", "Features", "IncomingEndpoint", "IncomingContentType", "IncomingHeader", "IncomingData", "OutgoingEndpoint", "OutgoingContentType", "OutgoingHeader", "OutgoingData", });
    internal_static_com_trasier_api_client_protobuf_Span_TagsEntry_descriptor =
      internal_static_com_trasier_api_client_protobuf_Span_descriptor.getNestedTypes().get(0);
    internal_static_com_trasier_api_client_protobuf_Span_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Span_TagsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_trasier_api_client_protobuf_Span_FeaturesEntry_descriptor =
      internal_static_com_trasier_api_client_protobuf_Span_descriptor.getNestedTypes().get(1);
    internal_static_com_trasier_api_client_protobuf_Span_FeaturesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Span_FeaturesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_trasier_api_client_protobuf_Span_IncomingHeaderEntry_descriptor =
      internal_static_com_trasier_api_client_protobuf_Span_descriptor.getNestedTypes().get(2);
    internal_static_com_trasier_api_client_protobuf_Span_IncomingHeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Span_IncomingHeaderEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_trasier_api_client_protobuf_Span_OutgoingHeaderEntry_descriptor =
      internal_static_com_trasier_api_client_protobuf_Span_descriptor.getNestedTypes().get(3);
    internal_static_com_trasier_api_client_protobuf_Span_OutgoingHeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Span_OutgoingHeaderEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_com_trasier_api_client_protobuf_Endpoint_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_trasier_api_client_protobuf_Endpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_trasier_api_client_protobuf_Endpoint_descriptor,
        new String[] { "Name", "IpAddress", "Port", "Hostname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
